Add to README.md file a table of content, default image and installation instructions
Coucat/Pokedex pull request #4
Opened 2022-02-11 04:29 UTC by Emmanuelcazlo

2022-02-12 04:57 UTC, pablo179 requested changes
nice job, just some tlittle comments

2022-02-12 04:57 UTC, pablo179 commented on README.md
> +    <summary>Table of Contents</summary>
very good add

2022-02-12 04:57 UTC, pablo179 commented on README.md
> +<a align="center"> <img src="https://res.cloudinary.com/dvxtbmch0/image/upload/v1644551448/Captura_de_pantalla_de_2022-02-10_21-50-18_va8kpv.png"  width="1000" /> </a>
let's use the image of the pokedex that we attempt to copy: https://dribbble.com/shots/15128634-Pokemon-Pokedex-Website-Redesign-Concept

2022-02-12 04:57 UTC, pablo179 commented on README.md
> +
also we need to add a reference like: this design is made by {author} and we get it from {link}

2022-02-12 04:57 UTC, pablo179 commented on README.md
> +```
we have the `yarn` commando too

2022-02-13 02:13 UTC, Emmanuelcazlo commented on README.md
> +```
that commands only replace npm ?

2022-02-13 03:38 UTC, pablo179 approved these changes
Just fix the conflict on the branch to merge

2022-02-16 00:07 UTC, merged